"use strict";
angular.module('api-config', [])
		.constant('ENV',
        {
            name: 'IOT Admin Panel Area',
			//apiEndpoint: 'http://{{ENV_APP_URL}}/',
            //userapiEndpoint: 'http://{{ENV_APP_URL}}/',
            wso2ServerEndpoint: 'http://10.107.0.158:82/',
			apiEndpoint: 'http://10.107.0.186/',
			userapiEndpoint: 'http://10.107.0.186/',
			 simulatorConnectionUrl :'10.103.2.251',
           	 simulatorConnectionPort :15675,
    //        apiEndpoint: 'http://10.115.2.12:8000/',
        //    apiEndpoint: 'http://198.199.110.151/', //Web-service Base URL,
        //    apiWebSocketPoint: 'ws://104.236.138.227:8000/wsproject/{0}/stream/',
        //    apiWebSocketPoint: 'ws://10.107.1.164:8000/wsproject/{0}/stream/',
           // apimqttConnectionUrl: '{{ENV_UI_BROKER_URL}}',
            apimqttConnectionUrl: '10.107.1.169',
           
            livemqttConnectionUrl: '10.107.1.169',
           // livemqttConnectionUrl: '{{ENV_UI_BROKER_URL}}',
           //apimqttConnectionUrl:    '{{ENV_UI_BROKER_URL}}',
            apimqttConnectionPort: 15675,
            //livemqttConnectionUrl: '{{ENV_UI_BROKER_URL}}',
			videoStreamingPath: 'rtsp://10.100.28.105:554/kroger',
		//    apiWebSocketPoint: 'ws://10.107.1.164:8000/wsproject/{0}/stream/',
			//apiWebSocketPoint: 'ws://10.107.2.204:8000/wsproject/{0}/stream/',
		    isLoggerEnabled: true, //TRUE: Enabled Loggin, FALSE: Disabled Loggin
			WSO2Mode: false,
			recordPerPage:10
        })

    //	Image Logo & Image Header Calls
    .constant('imageConstant', {

        companyLogoHeader: 'assets/Images/header.png',
        LogoHeader: 'assets/Images/logo4.png',
        LogoHeaderLogin: 'assets/Images/eiLogo.png',
    })
    //	Error Handling Done By Sanny Soni
    // http codes constants
 .constant('powerBIConstant', {
        microsoftUrl: 'https://login.microsoftonline.com/',
        authorizeAPI: '/oauth2/authorize',
        tenantId: 'bb23ef05-4d4a-4710-83e3-4e5d29f42540',
        clientId: 'd11effcf-72be-492a-8eb0-a3f2ca856cd8',
        redirectUri: 'http://10.107.1.166',
        responseType: 'code',
        responceMode: 'query',
        resource: 'https://analysis.windows.net/powerbi/api',
        state: '12345',
        azureGetToken: '/oauth2/token',
        grantType: 'authorization_code',
        clientSecret: 'm9APBKkNwTlUa7YvbtjyhJC5MZWkRjpKpDjLop/0bGQ=',
        dashboardEmbedURL: 'https://app.powerbi.com/dashboardEmbed?dashboardId={0}',
        dataset_powerbi: 'https://api.powerbi.com/v1.0/myorg/datasets',
        powerbi_datasets:'https://app.powerbi.com/groups/me/contentlist/datasets'
    })
    //	Error Handling Done By Sanny Soni
    // http codes constants
    .constant('httpErrors', {
        "-1": "Could not connect to Server. It is either down or please ensure the correct Server IP.",
        100: "Continue",
        101: "Switching Protocols",
        102: "Processing (WebDAV)",
        200: "OK",
        201: "Created",
        202: "Accepted",
        203: "Non-Authorative Information",
        204: "No Content",
        205: "Reset Content",
        206: "Partial Content",
        207: "Multi-Status (WebDAV)",
        208: "Already Reported (WebDAV)",
        226: "IM Used",
        300: "Multiple Choices",
        301: "Moved Permanently",
        302: "Moved Temporarily",
        303: "See Other",
        304: "Not Modified",
        305: "Use Proxy",
        306: "Unused",
        307: "Temporary Redirect",
        308: "Permanent Redirect (experiemental)",
        400: "Bad Request",
        401: "Authorization Required",
        402: "Payment Required",
        403: "Forbidden",
        404: "The requested data or service could not be found",
        405: "Method Not Allowed",
        406: "Not Acceptable",
        407: "Proxy Authentication Required",
        408: "Request Timed Out",
        409: "Conflicting Request",
        410: "Gone",
        411: "Content Length Required",
        412: "Precondition Failed",
        413: "Request Entity Too Long",
        414: "Request URI Too Long",
        415: "Unsupported Media Type",
        416: "Requested Range Not Satisfiable",
        417: "Expectation Failed",
        418: "I'm a teapot (RFC 2324)",
        420: "Enhance Your Calm (Twitter)",
        422: "Unprocessable Entity (WebDAV)",
        423: "Locked (WebDAV)",
        424: "Failed Dependency (WebDAV)",
        425: "Reserved for WebDAV",
        426: "Upgrade Required",
        428: "Precondition Required",
        429: "Too Many Requests",
        431: "Request Header Fields Too Large",
        444: "No Response (Nginx)",
        449: "Retry With (Microsoft)",
        450: "Blocked by Windows Parental Controls (Microsoft)",
        451: "Unavailable For Legal Reasons",
        499: "Client Closed Request (Nginx)",
        500: "Internal Server Error",
        501: "Not Implemented",
        502: "Bad Gateway",
        503: "Service Unavailable",
        504: "Gateway Timeout",
        505: "HTTP Version Not Supported",
        506: "Variant Also Negotiates (Experimental)",
        507: "Insufficient Storage (WebDAV)",
        508: "Loop Detected (WebDAV)",
        509: "Bandwidth Limit Exceeded (Apache)",
        510: "Not Extended",
        511: "Network Authentication Required",
        598: "Network read timeout error",
        599: "Network connect timeout error"
    })
    .constant('CustomMessages', {
        GATEWAY_DEREGISTER_POST_SUCCESS: "Successfully Deregistered.",
        GATEWAY_REGISTER_POST_SUCCESS: "Successfully Registered.",
        GATEWAY_REGISTER_POST_FIELD_ERROR: "Please Select the User",
        GATEWAY_DEACTIVATE_POST_SUCCESS: "Successfully Deactivated.",
        GATEWAY_ACTIVATE_POST_SUCCESS: "Successfully Activated.",
        GATEWAY_ACTIVATE_POST_ERROR: "Not Activated.",
        GATEWAY_DEACTIVATE_POST_ERROR: "Not Deactivated.",
        GATEWAY_LOGIN_SUCCESS: "Login Successful",
        GATEWAY_LOGIN_FAILURE: "Username or password is incorrect",
        GATEWAY_DISCOVER_OPC_ERROR: "OPCUrl Not to be blank.",
        GATEWAY_DISCOVER_PORT_ERROR: "Please select App Name.",
        GATEWAY_REBOOT_ERROR: "Please Select Gateway for reboot.",
        GATEWAY_TURNOFF_ERROR: "Please Select Gateway for turnoff.",
        GATEWAY_REBOOT_SUCCESS: "Selected gateway is successfully rebooted.",
        GATEWAY_TURNOFF_SUCCESS: "Selected gateway is successfully turnoff.",
        GATEWAY_REBOOT_ERROR_2: "Error Reboot Request Gateway.!",
        COMMON_MODAL_PASSWORD: "Password successfully updated. Please Login the Further Process.",
        COMMON_MODAL_PASSWORD_ERROR: "Error - Change Password Not Successfully Updated.",
        COMMON_MODAL_PROFILE_SUCCESS: "User Profile Successfully Updated.",
        COMMON_MODAL_PROFILE_ERROR: "Error - User Profile Not Successfully Updated.",
        APPLICATION_SUCCESSFULLY_DELETED: "Application Successfully Deleted.",
        APPLICATION_SUBSCRIPTION_SELECTED_OPTIONS: "Not selected options please Check any options",
        APPLICATION_SUBSCRIPTION_UPDATED_SUCCESS: "Subscription Updated Successfully.",
        DEVICE_WEBSOCKET_ERROR: "Devices not changed - Status In Progress",
        GATEWAY_BLE_PORT_SELECTION_ALERT: "Please select BLEPort.",
        GATEWAY_DEVICE_CHECKBOX_OPTIONS: "Not selected options please Select any option",
        GATEWAY_GENERAL_INFORMATION_ERROR: "General Information not changed - Status In Progress",
        GATEWAY_TASK_ERROR_REFRESH: "Error on Refresh Apps.",
        GATEWAY_TASK_ERROR_ENDED: "Error on App Ended.",
        GATEWAY_TASK_ERROR_RESTART: "Error on Restart App.",
        GATEWAY_TASK_SUCCESS_REFRESH: "Successfully Refresh Apps.",
        GATEWAY_TASK_SUCCESS_ENDED: "Successfully App Ended.",
        GATEWAY_TASK_SUCCESS_RESTART: "Successfully Restart App.",
        GATEWAY_TASK_ERROR_START: "Error on Start App.",
        GATEWAY_TASK_SUCCESS_START: "Successfully Start App.",
        GATEWAY_PACKAGE_SUCCESS_REFRESH: "Successfully Refresh Packages.",
        GATEWAY_PACKAGE_ERROR_REFRESH: "Error on Refresh Packages.",

        GATEWAY_PACKAGE_SELECTION_ERROR: "Please Select Package for upgrade",

        GATEWAY_PACKAGE_SUCCESS_UNINSTALL: "Successfully Uninstall Packages.",
        GATEWAY_PACKAGE_ERROR_UNINSTALL: "Error on Uninstall Packages.",

        GATEWAY_INSTALL_PACKAGE_SUCCESS: "Successfully Install Packages.",
        GATEWAY_INSTALL_PACKAGE_ERROR: "Error on Install Packages.",

        GATEWAY_UPDATE_PACKAGE_SUCCESS: "Successfully Update Packages.",
        GATEWAY_UPDATE_PACKAGE_ERROR: "Error on Update Packages.",

        SELECT_GATEWAY_ACTIVATE: "Please Select Gateway for activate.",
        SELECT_GATEWAY_DEACTIVATE: "Please Select Gateway for deactivate.",
        GATEWAY_ASSIGN_GROUP: "Successfully Assigned Groups of ",
        GATEWAY_BLANK_ERROR: "Gateway / User field is blank. Please select",
        GATEWAY_DEACTIVATE_POST_ERROR_2: "Please Select Valid Gateway for Deregister.",
        GROUP_DELETE_POST_SUCCESS: "Group Successfully Deleted.",
        GROUP_BLANK_ERROR: "Group name / Description not to be blank",
        GROUP_UPDATE_POST_SUCCESS: "Group Successfully Updated.",
        GROUP_INSERT_POST_SUCCESS: "Group Successfully Inserted.",
        FORGET_PASSWORD_EMAIL_SUCCESS: "User Information sent Successfully. Please check your mail.",
        TOKEN_ERROR: "Token Error For User Detail Credentials",
        LOGIN_ERROR: "Somehow not connected - Error From Server Connection.",
        ROLE_PERMISSION_ERROR: "'Please check any role permissions'",
        GATEWAY_GROUP_DELETED: "Selection of Gateway Group Deleted.",
        USER_TEMP_CREATE_ERROR: "Username Exists. Please select another username",
        MD_GENERAL_ARIA_LABEL: "Lucky day",
        MD_GENERAL_ARIA_LABEL_1: "Alert Dialog",
        MD_GENERAL_OK: "Yes",
        MD_GENERAL_GOT_IT: "Got It!",
        MD_GENERAL_CANCEL: "No",

            MD_DELETE_APPLICATION_TITLE: "Are you sure want to delete this Application?",
            MD_DELETE_APPLICATION_TEXT_CONTENT:"Mention Application should be deleted as per this action.",
            MD_DELETE_APPLICATION_TEXT_CONTENT1:"This action affected application management module",

            MD_SENID_TITLE:"Please Select Property",
            MD_SENID_TEXT_CONTENT:"You have to select Property of gateway.",
           
            MD_GATEWAY_SELECT_TITLE:"Please Select Address & SenId & Protocol",
            MD_GATEWAY_SELECT_TEXT_CONTENT:"You have to select Protocol / Address / SenId / Protocol of gateway.",

            MD_GROUP_DELETE_TITLE:"Are you sure want to delete this group?",
            MD_GROUP_DELETE_TEXT_CONTENT:"This action affected Groups Module",

            MD_EDIT_ROLE_TITLE: 'Are you sure you want to edit this Role?',
            MD_EDIT_ROLE_TEXT_CONTENT:'It will affect following users: ',
            MD_EDIT_ROLE_TEXT_CONTENT_2:'This role is not yet assigned to any user. ',
            MD_DELETE_ROLE_TITLE:"Are you sure want to delete this Role?",
            MD_DELETE_ROLE_TEXT_CONTENT:"Mention Role should be deleted as per this action.",

            MD_DELETE_USER_TITLE: "Are you sure you want to perform this Action?",
            MD_DELETE_USER_TEXT_CONTENT:"This action affected user management module",
			GATEWAY_ANYSELECTION_UNINSTALL_PACKAGE:"Please Select any option for Uninstall Package",

			GATEWAY_TRANSFER_DUPLICATE_SUCCESS: "Successfully Transfer App.",
			GATEWAY_TRANSFER_DUPLICATE_ERROR: "Error on Transfer App.",
			GATEWAY_DEVICE_OPC_ADDRESS_NULL: "Address field should not passing null - Device Register / Deregister / Active / Deactive.",
			
			GATEWAY_DUPLICATE_APP_SUCCESS: "Successfully Duplicate App.",
			GATEWAY_DUPLICATE_APP_ERROR: "Error on Duplicate App.",
			DEVICE_WEBSOCKET_NEW_DEVICE_NOT_FOUND: "New Device Not Found.",
	        DATA_UPDATED_SUCCESS:"Data Updated Successfully",
			DATA_UPDATED_FAILURE:"Not Updated"
		})
		.constant('apiConstant',
		{
        // Login
        login: 'api/users/login/',
		SetCredentials: 'api/users/userdetails/',
		gatewayAll: 'api/gateway/display/?format=json',
        gatewayDescription :'api/gateway/description/{0}/',
        gatewayTasks :'api/gateway/apps/{0}/',
        gatewayPackages : 'api/gateway/package/{0}/',
		getGatewayDetails:'api/gateway/{0}/',
		getGatewayNameANDIDOnly:'api/gateway/display/?format=json',
	//	getRegisteredUsersGateway:'api/filter/?object=Users',
		getRegisteredUsersGateway:'api/users/gatewayaccess_user_list/',
		getAllGatewayManager:'api/filter/?object={0}',
		setActivateANDDeactivatePostForm:'api/gateway/activation/',
		setRegisterPostForm:'api/gateway/assignment/{0}/',
		setDeregisterPostForm:'api/gateway/assignment/{0}/',
		getGatewayGroupsDetails:'api/gateway/getgroups/{0}/',
		getGatewayDiscover:'api/device/discovery/',
		postOPCActivationDataForm:'api/device/activation/',
		postOPCDataForm:'api/device/register/',
		postLiveData:'api/live/filterLiveData/',
		getJobList:'api/jobs/{0}/',
		getActivation:'api/gateway/activation/?gwid={0}',
		getDeviceData2:'api/devicefilter/?g_id={0}&d_appid={1}',
		getDeviceData:'api/device/?gwid={0}',
		getSubProperties:'api/deviceconfig/{0}/',
		getGatewayRequestManagers:'api/gateway/history/{0}/',
		getDeviceRequestManagers:'api/device/history/{0}/?d_id={1}&unit={2}&time={3}',
		getPropertyConstrain:'api/deviceproperty/{0}/?property={1}',
		getGatewayConfiguration:'api/gatewayconfig/{0}/',
		rebootData:'api/gateway/reboot/',
		getDeviceList:'api/devicefilter/?format=json',
		getApplicationsList:'api/orgs/?format=json',
		getApplicationDetailFromId:'api/orgs/{0}/',
		getOrganizationData:'api/orgs/',
		getSubscription:'api/apigroups/{0}/',
		getAPIGroups:'api/apigroups/?visibility=ORG',
		getGroupsList: 'api/groups/?format=json',
		getGroupsData: 'api/groups/listtree/',
		EditGroupRequest:'api/groups/{0}/',
		getUsersList:'api/users/?format=json',
		getUserRolesList:'api/roles/?format=json',
		getAllRoles:'api/roles/',
		roleEditNotification:'api/roles/role-update-notification/{0}/',
		sendRoleRequest:'api/roles/{0}/',
		sendRequest1 : 'api/users/activate/',
		sendRequest2 : 'api/users/deactivate/',
		postUserData : 'api/users/{0}/',
		forgetPassword : 'api/users/forgetpassword/',
		getTaskDetails : 'api/task/{0}/',
		PostTaskForm: 'api/task/manage_app/',
		DuplicateApp: 'api/task/duplicate_app/',
		TransferApp: 'api/task/transfer_owner/',
		PostConfigureForm: 'api/gatewayconfig/',
		CreateUserUrl: 'api/users/createtmpuser/',
		postUserData2 : 'api/users/?id={0}',
		changepassword: 'api/users/changepassword/',
		statusApplicationChangeRequest: 'api/orgs/{0}/{1}/',
		getEventsList: 'api/event/?g_id={0}',
		getDeviceEventsList: 'api/event/?orgid={0}&deviceid={1}',
		getAllUsers: 'api/filter/?object={0}',
		PackageRefresh: 'api/apps/get_app/',
		getApps: 'api/apps/',
		PackageInstall: 'api/apps/install_app/',
		PackageUninstall: 'api/apps/uninstall_app/',
		PackageUpdate: 'api/apps/update_app/',
	    postViewGetData: 'api/live/cisco_live/',
		getDeviceProperties: 'api/device/{0}/',
		getProperties:'api/device/',
		registerDeviceProperties:'api/deviceproperty/',
		refreshDeviceProperties:'api/devicestate/refreshproperties/',
		setDeviceProperties:'api/devicestate/setproperties/',
        addDeviceGroups:'api/devicegroup/',
        putdeleteDeviceGroups:'api/devicegroup/{0}/',
		trashGateway:'api/gateway/permanentdestroy/',
        actionProfiles:'api/devicesgroupsaction/',
        putdeleteActProf:'api/devicesgroupsaction/{0}/',
        getGatewayListSchdulerApp :'api/gateway/gatewaylist/',
        getDeviceScheduleInfo:'api/deviceactions/schedule_property_information/',
        getDevicePropertyScheduleInfo:'api/deviceactions/device_property_information/',
        postDeviceScheduledInfo:'api/deviceaction/',
        putDeviceScheduledInfo:'api/deviceaction/{0}/',
		getSubProperties:'api/deviceconfig/{0}/',
		putPropertyLockData:'api/propertyaccess/{0}/',
		postPropertyLockData:'api/propertyaccess/',
        getPropertyLockId:'api/propertyaccess/?d_id={0}',
        newRAMLDefinitionTemplate:'api/definition/',
		retrieveRAMLTemplate:'api/definition/{0}/',
		getServerApp: 'api/meshserver/',
		postServerData: 'api/meshserver/{0}/',
		assignGatewayToServer: 'api/meshserver/assigngateways/',
		ConfirmSaveDeployment: 'api/Bulk_software_update/install_bulk_software/',
		ConfirmUninstallDeployment: 'api/Bulk_software_update/uninstall_bulk_software/',
		ConfirmUpgradeDeployment: 'api/Bulk_software_update/upgrade_bulk_software/',
	    putRAMLDefinitionTemplate:'api/definition/{0}/',
        newRAMLDeviceTemplate:'api/raml_device_template/',
		setRAMLDevice:'api/raml_devices/set_raml/',
		getRAMLDevice:'api/raml_devices/get_raml/',
		deleteRAMLDefinitionTemplate:'api/raml_device_template/{0}/',
        retrieveRAMLDeviceTemplate:'api/definition/{0}/',
		getShdaowData:'api/devicestate/getdeviceproperties/{0}/',
		getShadowvalue : 'api/devicestate/getdeviceproperties/{0}/',
		getVendorModelIDForModbus: 'api/xml/xmlpublish/',
		setXMLLookup : 'api/xml/set_xml_lookup/?appid={0}&deviceid={1}&vendor={2}&modelid={3}',
		setXML : 'api/xml/',
		setXMLPARAM : 'api/xml/{0}/',
		updateLocalAndroidAccess:'api/localapp/update_local_appid/',
		getDockerApp : 'api/docker/',
		deleteDockerApp: 'api/docker/{0}/',
		getGatewayDocker: 'api/gatewaydocker/',
		deleteGatewayApp: 'api/gatewaydocker/{0}/',
		postProvision: 'api/gatewaydocker/gateway_provision/',
		getRuleEngineList: 'api/rule/',
		mainRulesedit: 'api/rule/{0}/',
		subRulesedit: 'api/subrule/{0}/?gwid={1}&appid={2}',
		subRulesAdd: 'api/subrule/?gwid={0}&appid={1}',
		meshgroup: 'api/meshsgroup/',
		getmeshList:'api/meshsgroup/',
		postMeshServer:'api/meshserver/',
		editmeshServer:'api/meshserver/{0}/?mid={1}',
		getmeshserverlist:'api/meshserver/?mid={0}',
		ruleEngineGatewayList: 'api/gateway/gatewaylist/',
		editMesh :'api/meshsgroup/{0}/',
		deletemeshServer: 'api/meshserver/{0}/',
		deviceListbygatewayId :'api/gateway/meshdevice/?meshid={0}',
		getmeshBygwid :'api/meshsgroup/meshbygateway/{0}/',
		putMeshDetailsinGateway:'api/gateway/gatewaymesh/{0}/',
		trashProvision:'api/gateway/del_gateway/',
		sendGatewayConfiguration:'api/gateway/gateway_config/',
		getFetchGatewayFromPackages: 'api/task/fetch_gateway/',
		baseUrlAppPost:'api/gatewayconfig/baseurl/?gwid={0}',
		cloudConnectivityApp:'api/gatewayconfig/cloudconnection/?gwid={0}',
		testConnection :'api/gatewayconfig/testconnection/?gwid={0}',
		localConnectivityApp:'api/gatewayconfig/localconnection/?gwid={0}',
		deployConnectivityApp:'api/gatewayconfig/deployconnection/?gwid={0}',
        mqttptlConnectivityApp:'api/gatewayconfig/simulator/?gwid={0}',
		fetchAppFromGateway: 'api/gatewayconfig/{0}/',
		getGatewaysFromMesh: 'api/meshsgroup/{0}/',
		getLatestApps: 'api/Bulk_software_update/app_version/',
		getDeviceRAML:'api/device_raml/get-raml/{0}',
		setDeviceRaml : 'api/raml_devices/set_raml/',
		deviceDeRegisterAll:'api/devices/register_all/',
		deviceDeactivationAll:'api/devices/activate_all/',
		getGatewayFromMesh:'api/meshsgroup/gatewaybymesh/{0}/',
		getAllRAMLDevice:'api/devices/device_raml_all/?appname={0}',
		postAccessData:'api/appaccess/',
		gwAccessControl:'api/appaccess/?gwid={0}&appname={1}',
		appaccesscontrol:'api/appaccess/create_list/',
		 callApi: 'api/azure/call_endpoint/',
        getPowerBIDevice: 'api//?deviceId={0}',
        getpowerbigateway: 'api/powerbi/power_bi_gateway/',
        getpowerbidevicebygwid: 'api/powerbi/power_bi_device/?gwid={0}',
        createdataset : 'api/powerbi/createdataset_powerbi/',
		getactiveProperties:'api/propertystatus/'
		})